[workspace]
resolver = "2"
members = ["egui-tabs", "examples/*"]

[workspace.package]
edition = "2021"
license = "MIT OR Apache-2.0"
rust-version = "1.72"
version = "0.26.2"

[workspace.dependencies]
egui_tabs = { path = "egui-tabs" }
egui = "0.29.1"
egui_extras = "0.29.1"
eframe = "0.29.1"
